export const riskdata = [
    "Subliminal Techniques",
    "Behavioral Manipulation",
    "Social Scoring",
    "Surveillance",
    "Facial Recognition",
    "Biometric Identification",
    "Emotion Recognition",
    "Deceptive Practices",
    "Automated Misinformation",
    "Disinformation Campaigns",
    "Targeted Advertising",
    "Vulnerable Population",
    "Children's Data",
    "Covert Monitoring",
    "Deepfakes",
    "Pseudoscience",
    "Uninformed Consent",
    "Non-consensual Data Use",
    "Exploitation of Vulnerability",
    "Mass Surveillance",
    "Policing",
    "Personalized Propaganda",
    "Automated Decision-Making",
    "Discriminatory Profiling",
    "Coercion",
    "Mental Manipulation",
    "Unethical Persuasion",
    "Biased Algorithms",
    "Unauthorized Access",
    "Privacy Invasion",
    "Unlawful Discrimination",
    "Human Rights Violation",
    "Autonomous Weaponry",
    "Manipulative Content",
    "Psychological Harm",
    "Invasive Data Collection",
    "Emotionally Exploitative",
    "Political Manipulation",
    "Coercive Control",
    "Unauthorized Data Processing",
    "Psychographic Targeting",
    "Dark Patterns",
    "Identity Theft",
    "Excessive Data Retention",
    "Secret Surveillance",
    "Algorithmic Bias",
    "Exploitation of Bias",
    "Data Misuse",
    "Involuntary Profiling",
    "Unregulated Experimentation",
    "Critical Infrastructure",
    "Healthcare Diagnostics",
    "Medical Devices",
    "Autonomous Vehicles",
    "Employment Decisions",
    "Educational Testing",
    "Loan Approval",
    "Credit Scoring",
    "Law Enforcement",
    "Judicial Systems",
    "Surveillance Technology",
    "Border Control",
    "Immigration Processing",
    "Biometric Data Processing",
    "Digital Identity",
    "Public Safety",
    "Predictive Analytics",
    "Risk Assessment",
    "Cybersecurity",
    "Content Moderation",
    "Consumer Protection",
    "Remote Sensing",
    "Energy Grid Management",
    "Supply Chain Logistics",
    "Public Health Monitoring",
    "AI in Warfare",
    "Insurance Underwriting",
    "Critical Communications",
    "Emergency Response",
    "Infrastructure Monitoring",
    "Financial Fraud Detection",
    "Remote Workforce Management",
    "AI-driven Hiring",
    "Virtual Reality Training",
    "Security Screening",
    "AI in Education",
    "Autonomous Drones",
    "Natural Disaster Prediction",
    "Crowd Control",
    "Data Breach Response",
    "Personalized Medicine",
    "Genetic Data Processing",
    "Transportation Safety",
    "Building Automation",
    "AI for Decision Support",
    "Military Applications",
    "AI in Governance",
    "Public Transport Management",
    "Environmental Monitoring",
    "AI in Finance",
    "Chatbots",
    "Virtual Assistants",
    "Customer Support Automation",
    "Content Recommendation",
    "Sentiment Analysis",
    "Personalization",
    "Email Filtering",
    "Autocorrect",
    "Predictive Text",
    "Social Media Algorithms",
    "Image Recognition",
    "Language Translation",
    "Speech Recognition",
    "Content Curation",
    "Digital Advertising",
    "E-commerce Recommendations",
    "Product Suggestions",
    "Voice Assistants",
    "Interactive Voice Response",
    "Automated Messaging",
    "Chat Moderation",
    "Behavioral Targeting",
    "Dynamic Pricing",
    "Conversational AI",
    "User Engagement",
    "Gamification",
    "Augmented Reality",
    "Recommendation Engines",
    "Personal Finance Management",
    "Fitness Trackers",
    "Entertainment Recommendations",
    "Music Streaming Suggestions",
    "Video Content Suggestion",
    "User Preferences",
    "Ad Personalization",
    "Text Summarization",
    "Voice Cloning",
    "Video Editing AI",
    "AI-powered Creativity",
    "Virtual Characters",
    "Digital Twins",
    "AR Filters",
    "Customer Journey Mapping",
    "AI-driven Personalization",
    "Emotion Detection",
    "Facial Filters",
    "Interactive Storytelling",
    "Data-driven Insights",
    "AI-driven Surveys",
    "Content Moderation Alerts",
    "Entertainment AI",
    "Video Game AI",
    "Movie Recommendations",
    "Music Playlists",
    "Smart Home Automation",
    "Lighting Control",
    "Voice-controlled Devices",
    "Fitness Coaching",
    "Recipe Suggestions",
    "Calendar Management",
    "Weather Forecasting",
    "Simple Task Automation",
    "Spam Filtering",
    "Search Engine Optimization",
    "Language Learning Apps",
    "Personal Reminders",
    "Alarm Systems",
    "Home Security Monitoring",
    "News Aggregation",
    "Online Shopping Assistance",
    "Photo Editing Tools",
    "Video Enhancement",
    "Augmented Reality Games",
    "Background Noise Reduction",
    "Smart Thermostats",
    "Energy Usage Monitoring",
    "Virtual Pet Companions",
    "Reading Recommendations",
    "AI-driven Art Creation",
    "Fitness Goal Tracking",
    "Step Counters",
    "Mindfulness Apps",
    "Sleep Tracking",
    "Automated Email Responses",
    "Social Media Scheduling",
    "Simple Language Translation",
    "Voice Notes",
    "Basic Data Entry Automation",
    "Reminder Notifications",
    "AI-driven Calendar Suggestions",
    "Simple Survey Tools",
    "Home Lighting Schedules",
    "Voice-activated Reminders",
    "Routine Task Management",
    "Daily Horoscope",
    "Automated To-do Lists",
    "TV Show Recommendations",
    "AI-driven Background Music",
    "Simple Chatbots for FAQs",
    "Automated Social Media Posts",
]